Use hosts.prod for every branch with siffix ".prod"

diff --git a/git-hook-post-checkout b/git-hook-post-checkout
--- a/git-hook-post-checkout
+++ b/git-hook-post-checkout
@@ -1,9 +1,15 @@
-#!/bin/sh
+#!/bin/bash
 
 # Do nothing if branch didn't change 
 test "$3" = "1" || exit 0
-current_branch=$(git rev-parse --abbrev-ref HEAD)
-ln -sf hosts.$current_branch hosts \
-&& echo "Link: hosts -> hosts.$current_branch" \
-|| echo "Failed to create link hosts -> hosts.$current_branch"
 
+function mklink() {
+ln -sf hosts.$1 hosts && echo "Link: hosts -> hosts.$1" || echo "Failed to create link hosts -> hosts.$1";
+}
+
+current_branch=$(git rev-parse --abbrev-ref HEAD)
+if [[ "$current_branch" = "prod" || "$current_branch" = *".prod" ]]; then
+        mklink prod
+else
+        mklink test
+fi
